== trema コマンド

=== trema run

コントローラを実行する。

----
$ trema run [コマンドオプション] コントローラ
----

==== 使い方

コントローラを実行するには、`trema run` の引数にコントローラのファイル名を次のように渡す。実行したコントローラは `Ctrl + c` で停止できる。

----
$ trema run hello_trema.rb
----

デフォルトでは、コントローラは OpenFlow 1.0 モードで起動する。OpenFlow 1.3 を使いたい場合には、`--openflow13` オプションを指定する。

----
$ trema run hello_trema.rb --openflow13
----

仮想ネットワーク上でコントローラを動かす場合には、`trema run` の `-c` (`--conf`) オプションに仮想ネットワーク定義ファイルを指定する。

----
$ trema run hello_trema.rb -c trema.conf
----

コントローラをデーモンプロセスとして起動する場合には、`-d` (`--daemonize`) オプションを指定する。

----
$ trema run hello_trema.rb -c trema.conf -d
----

==== コマンドオプション一覧

|===
| コマンドオプション | 説明 | デフォルト値

| `-c`, `--conf` | 仮想ネットワークの定義ファイルを指定する |
| `-d`, `--daemonize` | コントローラをデーモンプロセスとして起動する |
| `--openflow13` | コントローラを OpenFlow 1.3 モードで起動する |
| `-L`, `--log_dir` | コントローラプロセスのログファイル (`コントローラ名.log`) を生成するディレクトリを指定する。 | `/tmp`
| `-P`, `--pid_dir` | コントローラプロセスの PID ファイル (`コントローラ名.pid`) を生成するディレクトリを指定する。 | `/tmp`
| `-S`, `--socket_dir` | コントローラのソケットファイル (`コントローラ名.ctl`) を生成するディレクトリを指定する。| `/tmp`
| `-l`, `--logging_level` | コントローラプロセスのロギングレベルを指定する。 | `info`
| `-p`, `--port` | コントローラプロセスがスイッチからの接続を待ち受ける TCP ポート番号を指定する | 6653
|===


=== trema dump_flows

指定したスイッチのすべてのフローエントリを表示する。

----
$ trema dump_flows [コマンドオプション] スイッチ名
----

==== 使い方

仮想ネットワーク設定で `of_switch` という名前のスイッチを定義し、コントローラを実行したとする。

[source,ruby,subs="verbatim,attributes"]
.trema.conf
----
vswitch('of_switch') { datapath_id 0xabc }
----

.コントローラを実行する
----
$ trema run my_controller.rb -c trema.conf
----

このときコントローラがスイッチ `of_switch` に書き込んだフローエントリを表示するには、次のように `trema dump_flows of_switch` を実行する。

----
$ trema dump_flows of_switch
cookie=0x0, duration=10.727s, table=0, n_packets=0, n_bytes=0, priority=0 actions=drop
----

出力フォーマットは Open vSwitch の `ovs-ofctl dump-flows` コマンドと同じ。詳しくは `man ovs-ofctl` の Table Entry Output を参照。

==== コマンドオプション一覧

|===
| コマンドオプション | 説明 | デフォルト値

| `-S`, `--socket_dir` | コントローラプロセスのソケットファイル (`trema.コントローラ名.ctl`) があるディレクトリを指定する。これは `trema run` コマンドの `-S`, `--socket_dir` オプションで指定した値を指定すればよい | `/tmp`
|===
