= OpenFlow1.3版ラーニングスイッチ
:sourcedir: vendor/learning_switch
:imagesdir: images/learning_switch

== OpenFlow1.3版ラーニングスイッチの仕組み

== ソースコード解説

OpenFlow1.3版パッチパネルのソースコードは<<learning_switch13.rb>>になります。

[[learning_switch13.rb]]
[source,ruby,subs="verbatim,attributes"]
.lib/learning_switch13.rb
----
include::{sourcedir}/lib/learning_switch13.rb[]
----

=== switch_ready ハンドラ

`switch_ready` ハンドラでは、まだ学習していないパケットのデフォルト処理を新しく起動したスイッチのフローテーブルに書き込みます。

[source,ruby,subs="verbatim,attributes"]
.LearningSwitch13#switch_ready (lib/learning_switch13.rb)
----
include::{sourcedir}/lib/learning_switch13.rb[lines="12..16"]
----

最初に呼び出す `add_multicast_mac_drop_flow_entry` では、IP マルチキャストフレームをドロップするフローエントリを書き込みます。

[source,ruby,subs="verbatim,attributes"]
.LearningSwitch13#add_multicast_mac_drop_flow_entry (lib/learning_switch13.rb)
----
include::{sourcedir}/lib/learning_switch13.rb[lines="47..56"]
----

Flow Mod に指定するパラメータのうちポイントとなるのは次の 3 つです。

- `table_id`: スイッチに入ってきたパケットの種類を見てドロップするかどうかを最初にフィルタリングする必要があるので、`table_id` には 0 (`INGRESS_FILTERING_TABLE_ID`) を指定します。
- `idle_timeout`: IPマルチキャストフレームのドロップはスイッチの起動中はずっと有効なので、`idle_timeout` には 0 (フローエントリを消さない) を指定します。
- `priority`: ドロップ処理は入ってきたパケットに対して最初に行うフィルタリングなので、テーブルID = 0 のフローエントリのうち最大優先度にします。ここでは 2 を指定します。

続く `add_default_forwarding_flow_entry` では、IP マルチキャストフレーム以外のパケットを `FORWARDING_TABLE_ID` で処理します。

[source,ruby,subs="verbatim,attributes"]
.LearningSwitch13#add_default_forwarding_flow_entry (lib/learning_switch13.rb)
----
include::{sourcedir}/lib/learning_switch13.rb[lines="58..67"]
----

ここで重要なパラメータは次の 3 つです。

- `priority` を 1 に設定することで、より優先度の高いIPマルチキャストフレーム処理 (優先度 = 2) が終わったあとにこの処理を行います。
- `match` 空のマッチを指定するので、IPマルチキャストフレームでないパケットをすべてこのフローエントリで拾います。
- `instructions` では `GotoTable(FORWARDING_TABLE_ID)` を指定することで、以降の処理をテーブル 1 に移します。

// TODO ソースコードの優先度がまちがってるのであとで修正する

最後の `add_default_flooding_flow_entry` では、宛先 MAC アドレスをまだ学習していない場合のデフォルト処理をフローテーブルに書き込みます。

[source,ruby,subs="verbatim,attributes"]
.LearningSwitch13#add_default_flooding_flow_entry (lib/learning_switch13.rb)
----
include::{sourcedir}/lib/learning_switch13.rb[lines="35..45"]
----

- `table_id`: ここで追加するフローエントリは、直前の GotoTable でテーブル ID INGRESS_FILTERING_TABLE_ID から FORWARDING_TABLE_ID に移動した後に処理されます。ですので、`table_id` には `FORWARDING_TABLE_ID` を指定します。
- `priority`: フラッディング処理は宛先 MAC アドレスをまだ学習していなかった場合のデフォルト処理なので、優先度は低めの 1 を指定します。
- `instructions`: フラッディングのための `SendOutPort.new(:flood)` アクションと、Packet In を起こするための `SendOutPort.new(:controller)` を `Apply` インストラクションで適用します。

=== packet_in ハンドラ

`packet_in` ハンドラでは、Packet In したパケットの送信元 MAC アドレス + In Port の組を学習します。

[source,ruby,subs="verbatim,attributes"]
.LearningSwitch13#switch_ready (lib/learning_switch13.rb)
----
include::{sourcedir}/lib/learning_switch13.rb[lines="24..33"]
----

ここでの Flow Mod パラメータのポイントは次のとおりです。

- `priority`: 優先度を `FORWARDING_TABLE_ID` の他のフローエントリ (フラッディング) よりも高くすることで、このフローエントリにマッチしない場合だけフラッディングするようにします。
- `idle_timeout`: フローエントリの寿命を指定しておくことで、OpenFlow1.0 版のラーニングスイッチで行ったタイマによるエイジングと同じ効果を出せます。
- `match`, `instructions`: 宛先が Packet In の送信元 MAC アドレスと同じだったら、Packet In の `in_port` から入ったパケットをそちらに送る、というエントリを入れています。

=== アクション一覧

[[actions1.3]]
.表 7-? OpenFlow 1.3 で使えるアクション一覧
|===
| アクションのクラス名 | 説明

| `SendOutPort` | 指定したスイッチの (論理) ポートにパケットを出力する
| `CopyTtlOut` | 二番目に外側のTTLの値を一番外側のTTLにコピーする
| `CopyTtlIn` | 一番外側のTTLの値を一つ内側のTTLにコピーする
| `SetMplsTtl` | MPLSのTTLをセットする
| `DecrementMplsTtl` | MPLSのTTLを1つ減らす
| `PushVlanHeader` | 新しいVLANヘッダをパケットに追加する
| `PopVlanHeader` | 一番外側のVLANヘッダをパケットから取り除く
| `PushMpls` | 新しいMPLSシムヘッダをパケットに追加する
| `PopMpls` | 一番外側のMPLSタグまたはシムヘッダをパケットから取り除く
| `SetQueue` | `SendOutPort`で指定したポートの指定したキューにパケットを追加する
| `Group` | 指定したグループテーブルでパケットを処理する
| `SetIpTtl` | IPv4のTTLまたはIPv6のhop limitをセットする
| `DecrementIpTtl` | IPv4のTTLまたはIPv6のhop limitを1つ減らす
| `SetField` | 指定したフィールドをパケットにセットする
| `PushPbb` | 新しいPBBサービスインスタンスヘッダ (I-TAG TCI) をパケットに追加する
| `PopPbb` | 一番外側のPBBサービスインスタンスヘッダ (I-TAG TCI) をパケットから取り除く
|===

// TODO SemdOutPort 以外を実装する

=== インストラクション一覧

[[instructions1.3]]
.表 7-? OpenFlow 1.3 で使えるインストラクション一覧
|===
| インストラクションのクラス名 | 説明

| `GotoTable` | マッチしたパケットの処理を指定したテーブルに引き継ぐ
| `WriteMetadata` | テーブル間で引き継げる 64bit のメタデータをセット
| `WriteActions` | アクションセットに指定したアクションを追加する
| `Apply` | 指定したアクションを実行する
| `Clear` | アクションセットを空にする
| `Meter` | パケットを指定したメーターに適用する
|===

// TODO: それぞれの詳しい説明を独立した節に書く
// TODO: それぞれが初登場する章へのリンクを張る
// TODO: クラス名を考え直す。Apply -> ApplyActions? Clear -> ClearActionSet? などなど
// TODO: WriteActions インストラクションは未実装
// TODO: Clear インストラクションは未実装

== まとめ
