=== trema run

コントローラを実行する。

----
$ ./bin/trema run [コマンドオプション] コントローラファイル
----

==== 使い方

コントローラを実行するには、`trema run` の引数にコントローラのファイル名を次のように渡す。実行したコントローラは kbd:[Ctrl + c] で停止できる。

----
$ ./bin/trema run hello_trema.rb
----

デフォルトでは、コントローラは OpenFlow 1.0 モードで起動する。OpenFlow 1.3 を使いたい場合には、`--openflow13` オプションを指定する。

----
$ ./bin/trema run hello_trema.rb --openflow13
----

仮想ネットワーク上でコントローラを動かす場合には、`trema run` の `-c` (`--conf`) オプションに仮想ネットワーク定義ファイルを指定する。

----
$ ./bin/trema run hello_trema.rb -c trema.conf
----

コントローラをデーモンプロセスとして起動する場合には、`-d` (`--daemonize`) オプションを指定する。

----
$ ./bin/trema run hello_trema.rb -c trema.conf -d
----

==== コマンドオプション一覧

|===
| コマンドオプション | 説明 | デフォルト値

| `-c`, `--conf` | 仮想ネットワークの定義ファイルを指定する |
| `-d`, `--daemonize` | コントローラをデーモンプロセスとして起動する |
| `--openflow13` | コントローラを OpenFlow 1.3 モードで起動する |
| `-L`, `--log_dir` | コントローラプロセスのログファイル (`コントローラ名.log`) を生成するディレクトリを指定する。 | `/tmp`
| `-P`, `--pid_dir` | コントローラプロセスの PID ファイル (`コントローラ名.pid`) を生成するディレクトリを指定する。 | `/tmp`
| `-S`, `--socket_dir` | コントローラのソケットファイル (`コントローラ名.ctl`) を生成するディレクトリを指定する。| `/tmp`
| `-l`, `--logging_level` | コントローラプロセスのロギングレベルを指定する。 | `info`
| `-p`, `--port` | コントローラプロセスがスイッチからの接続を待ち受ける TCP ポート番号を指定する | 6653
|===
